# Usage

While most of the examples here are mathematics-oriented, most features of this package should work for all sorts of functions.

In [13]:
from functionplus import Function

from math import factorial
import numpy as np

## Wrapping
To get started, we can use `Function` as a decorator for the function we want.

In [14]:
@Function
def f(x: float) -> float:
    return 2.5 * x

g = Function(lambda x: x**2, "g")

h = Function(np.cos, "h")

f, g, h

(<Function 'f'>, <Function 'g'>, <Function 'h'>)

These functions can then be called as normal; that said, you can also use the `function` attribute to access the underlying function if needed.

In [15]:
f(2), g.function(3)

(5.0, 9)

## Composition

To compose functions, we can use the `@` operator.

In [16]:
comp = f @ g
comp(2)  # equivalent to 2.5 * x**2

10.0

`Function`s can also be composed with regular callables, which limits the number of necessary `Function` wrappings.

In [17]:
comp2 = f @ abs  # no Function(abs) required
comp2(-2)  # equivalent to 2.5 * abs(-2)

5.0

If you left-compose a function with a non-callable, the result always maps its input to that value; if the input is an array, the output will then match the shape of the array.

In [18]:
(1 @ g)(3), ("hi" @ g)(np.arange(5))

(1, array(['hi', 'hi', 'hi', 'hi', 'hi'], dtype=object))

## Identity Function
To get the identity function $y(x) = x$, simply use the `id` class method.

In [19]:
identity = Function.id()
identity(3)

3

Since `Function`s can be composed with regular callables, composing one of them with `id` is effectively equivalent to the wrapping method.

In [20]:
x = Function.id("x")
p = np.exp @ x
p  # # equivalent to Function(np.exp)

<Function 'x; exp'>

The identity can also be used to, for example, create series representations of mathematical functions.

In [21]:
series = sum(x**n/factorial(n) for n in range(30))
series.name = "expseries"
series(1)  # very close to e

2.7182818284590455

## Arithmetic
Functions can be used in arithmetic expressions involving both other functions and , as shown below.

In [22]:
a = 2 + f + g - (h // 4)  # equivalent to a(x) = f(x) + g(x) - (h(x) // 4)

b = f**g % 5 + np.arctan # equivalent to b(x) = (f(x)^g(x) mod 5) + arctan(x)

c = abs(-f)*g/(2*(f // 4) + g*3)  # equivalent to c(x) = |-f(x)| g(x)/(2f(x) + g(x))

a(0), b(1), c(2)

(2.0, 3.2853981633974483, 1.4285714285714286)

## Boolean Logic
Functions can also be used with the boolean comparison operators shown below.

In [23]:
display(
    ((f > g) & (x >= 0))(np.linspace(-1, 1)),
    (f == g)(2.5),
    (abs(h) == 1)(np.pi/4 * np.arange(8)),
    ((1 < f) ^ (h <= 2))(np.linspace(0, np.pi)),
    (((x // 2) <= 2) | (x == 9))(np.arange(10))
)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

True

array([ True, False, False, False,  True, False, False, False])

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

array([ True,  True,  True,  True,  True,  True, False, False, False,
        True])

## Components

A set containing all of functions used to create a `Function` instance can be found in its `components` attribute.

In [24]:
c.components

{<function __main__.<lambda>(x)>,
 <function functionplus.function.Function.id.<locals>.<lambda>(x)>,
 <function __main__.f(x: float) -> float>,
 <ufunc 'cos'>}